import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FormProvider } from "./context/FormContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Form Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FormProvider>
      <html lang="en">
        <link rel="shortcut icon" href="https://media.licdn.com/dms/image/v2/C4D0BAQGjCtiL8FcUcw/company-logo_100_100/company-logo_100_100/0/1646835555234/peerlist_logo?e=1741824000&v=beta&t=GWDJ9UdJR4SLHhzLSWnaRCkScbWJoYT9n8e3ykR2DP8" />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </FormProvider>

  );
}
